services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:16
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sat
      - POSTGRES_USER=sat
      - POSTGRES_PASSWORD=sat

  dev:
    build:
      context: .
    container_name: sat_dev
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}:/home/sat/work
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis

  celery_dev:
    build:
      context: .
    command: celery -A core worker --loglevel=info
    env_file:
      - .env.dev
    volumes:
      - ${PWD}:/home/sat/work
    depends_on:
      - redis

  celery_prod:
    build:
      context: .
    command: celery -A core worker --loglevel=info
    env_file:
      - .env.prod
    volumes:
      - ${PWD}:/home/sat/work
    depends_on:
      - redis

  prod:
    build:
      context: .
    container_name: sat_prod
    ports:
      - "80:80"
    volumes:
      - ${PWD}:/home/sat/work
    command: gunicorn core.wsgi:application --bind 0.0.0.0:80 --workers 3
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data: