# Generated by Django 5.2 on 2025-04-05 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('DEBIT', 'Debit Account'), ('CREDIT', 'Credit Account'), ('SAVINGS', 'Savings Account')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consolidated Account',
                'verbose_name_plural': 'Consolidated Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.account')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Credit Account',
                'verbose_name_plural': 'Credit Accounts',
            },
            bases=('finance.account',),
        ),
        migrations.CreateModel(
            name='DebitAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.account')),
            ],
            options={
                'verbose_name': 'Debit Account',
                'verbose_name_plural': 'Debit Accounts',
            },
            bases=('finance.account',),
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.account')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_interest_calculation', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Savings Account',
                'verbose_name_plural': 'Savings Accounts',
            },
            bases=('finance.account',),
        ),
        migrations.CreateModel(
            name='ConsolidatedBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debit_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('savings_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Consolidated Balances',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense'), ('TRANSFER', 'Transfer'), ('CREDIT_PAYMENT', 'Credit Payment')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account')),
                ('related_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='finance.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
